use_frameworks!

platform :ios, '8.0'

target 'LLPhotoBrowser_Example' do
  pod 'LLImageBrowser', :path => '../'

  pod 'SDWebImage', '~> 4.4.1'

  target 'LLPhotoBrowser_Tests' do
    inherit! :search_paths

    
  end
end

